## Python Libraries For Data Science

Data science is the process of deriving knowledge and insights from a huge and diverse set of data through organizing,processing and analyzing the data.

There are nearly 20 python libraries for Data science.Top five python libraries are
* Tensorflow
* Numpy
* scipy
* pandas
* Matplotlib

In those libraries Numy and pandas are the first choice to the data scientists who are ware of the technologies.

### NumPyt:(Numerical Python)
Numpy is Base N-Dimenstional Array Package is a python library and a fundamental package for scientific computing in python.It is used to create multidimensional arrays for fast opearations.Use the followiing import conversion.

#### Numpy Array
Numpy have a fixed size of arrays used to store a collection of elements unlike python lists.There are three types of arrays called 1D,2D and 3D arrays.

### Advantages of Numpy:

We can write vectorized code on numpy arrays,not on lists.Which is convenient to read and write.
Vectorised code typically does not contain explicit looping and indexing etc.
Numpy is much faster than the standard python ways to do computaions

In [2]:
import numpy as np
# Creating array using numpy
k=np.array([2,5,3,5])
print(k)
print(type(k))

[2 5 3 5]
<class 'numpy.ndarray'>


In [5]:
# Program to find multiplication of numbers using lists
list1=[1,3,5,7]
list2=[2,4,6,8]
h=list(map(lambda t1,t2:t1*t2,list1,list2))
print(h)

[2, 12, 30, 56]


In [7]:
# Program to find multiplication of lists using Numpy
n1=np.array(list1)
n2=np.array(list2)
n1*n2

array([ 2, 12, 30, 56])

In [11]:
## Declaration of 2D array
import numpy as np
two_d=np.array([[1,2,3],[4,5,6]])
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
two_d[1]

array([4, 5, 6])

In [13]:
two_d[1:]


array([[4, 5, 6]])

In [14]:
two_d[1,2]

6

In [15]:
two_d[::]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
two_d[:,1] #Retrieve paricular column elements

array([2, 5])

In [18]:
# Creating Array with all elements are 1's
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
np.ones([5,5],dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.zeros([2,4],dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
np.full([3,4],5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [27]:
# Creating array with random numbers
np.random.random(10)

array([0.47917892, 0.08578725, 0.47670461, 0.85810333, 0.69825462,
       0.07260483, 0.62434645, 0.56048905, 0.62140942, 0.6063551 ])

In [28]:
np.random.randint(10,20,[4,5])

array([[17, 13, 14, 15, 14],
       [12, 16, 16, 18, 16],
       [12, 12, 15, 18, 18],
       [17, 12, 18, 14, 13]])

In [29]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
# Difference between time of list and numpy
list1=[i for i in range(1,1000000)]
list2=[j**2 for j in range(1,1000000)]

import time

t1=time.time()

op=list(map(lambda i,j:i*j,list1,list2))
t2=time.time()
final_time=t2-t1
print(final_time)

n1=np.array(list1)
n2=np.array(list2)

t3=time.time()
op=n1*n2
t4=time.time()
final_time2=t4-t3

print(final_time2)

0.24001383781433105
0.026001453399658203


In [36]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
g=np.arange(1,25).reshape(4,3,2)
print(g)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [45]:
g[1,:,:]

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [46]:
print("shape:{}".format(np.shape(g)))

shape:(4, 3, 2)


In [48]:
print("Datatype:{}".format(np.dtype(g)))

TypeError: data type not understood

In [59]:
print("Dimensions:{}".format(np.ndim(g)))

Dimensions:3


In [60]:
a1=np.arange(1,13).reshape(4,3)
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
a2=np.arange(10,22).reshape(3,4)
a2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [62]:
a1.dot(a2)

array([[ 92,  98, 104, 110],
       [218, 233, 248, 263],
       [344, 368, 392, 416],
       [470, 503, 536, 569]])

In [65]:
a1*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [52]:
# Inorder to find the det of any matrix it should be 
a3=np.arange(1,17).reshape(4,4)
a3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [53]:
np.linalg.inv(a3)

array([[ 3.94064967e+15, -4.50359963e+15, -2.81474977e+15,
         3.37769972e+15],
       [-4.12829966e+15,  4.50359963e+15,  3.37769972e+15,
        -3.75299969e+15],
       [-3.56534971e+15,  4.50359963e+15,  1.68884986e+15,
        -2.62709978e+15],
       [ 3.75299969e+15, -4.50359963e+15, -2.25179981e+15,
         3.00239975e+15]])

In [54]:
np.linalg.det(a3)

4.7331654313261276e-30

In [55]:
np.log(a3)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665],
       [2.56494936, 2.63905733, 2.7080502 , 2.77258872]])

In [56]:
np.tile([1,2,3],[2,3])

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [58]:
np.linalg.eig(a3)

(array([ 3.62093727e+01, -2.20937271e+00, -3.36399340e-15, -2.27991821e-16]),
 array([[-0.15115432,  0.72704996,  0.50279479, -0.10141287],
        [-0.34923733,  0.28320876, -0.83232136, -0.26597234],
        [-0.54732033, -0.16063243,  0.15625837,  0.83618329],
        [-0.74540333, -0.60447363,  0.17326821, -0.46879808]]))

### Task
Create a array of 1's.Take a list & convert it into a 3D array and add 1 to each element in an array

In [77]:
a=np.ones([3,4],dtype="int")
list1=np.arange(1,13)
con=list1.reshape(2,2,3)
add=con+1
print(add)

[[[ 2  3  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]]


In [78]:
a=np.ones([3,4],dtype="int")
con=a.reshape(2,2,3)
add=con+1
print(add)

[[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]
